 
version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    volumes: 
      - ./:/usr/src/app
    ports: 
      - '5000:5000'
    links:
      - mongo
    environment: 
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/web-dev
      - SECRET_OR_KEY=Vx6VScMm9kz6ko
  mongo:
    container_name: mongo
    image: mongo:4.0.4
    ports:
      - '27017:27017'